config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/ewl'
  get 'home/nsl'
  get 'home/ccl'
  get 'home/bplrt'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :layout => false
  end
  def ewl
    jsonFiles = File.read("EWL.json")
    jsonArray = JSON.parse(jsonFiles)
    timestampArray = []
    jsonArray.each do |jsonItem|
      if jsonItem["text"].include? "[EWL]"
        timestampObj = DateTime.strptime(jsonItem['timestamp'], '%Y-%m-%dT%H:%M:%S')
        timestampObj = timestampObj + 8.hours
        timestampArray.push((timestampObj.change(:offset => '+0800')).to_date)
        timestampArray = timestampArray.uniq.sort()
      end
    end
    @timestampArray = timestampArray
  end
  def nsl
    jsonFiles = File.read("NSL.json")
    jsonArray = JSON.parse(jsonFiles)
    timestampArray = []
    jsonArray.each do |jsonItem|
      if jsonItem["text"].include? "[NSL]"
        timestampObj = DateTime.strptime(jsonItem['timestamp'], '%Y-%m-%dT%H:%M:%S')
        timestampObj = timestampObj + 8.hours
        timestampArray.push((timestampObj.change(:offset => '+0800')).to_date)
        timestampArray = timestampArray.uniq.sort()
      end
    end
    @timestampArray = timestampArray
  end
  def ccl
    jsonFiles = File.read("CCL.json")
    jsonArray = JSON.parse(jsonFiles)
    timestampArray = []
    jsonArray.each do |jsonItem|
      if jsonItem["text"].include? "[CCL]"
        timestampObj = DateTime.strptime(jsonItem['timestamp'], '%Y-%m-%dT%H:%M:%S')
        timestampObj = timestampObj + 8.hours
        timestampArray.push((timestampObj.change(:offset => '+0800')).to_date)
        timestampArray = timestampArray.uniq.sort()
      end
    end
    @timestampArray = timestampArray
  end
  def bplrt
    jsonFiles = File.read("BPLRT.json")
    jsonArray = JSON.parse(jsonFiles)
    timestampArray = []
    jsonArray.each do |jsonItem|
      if jsonItem["text"].include? "[BPLRT]"
        timestampObj = DateTime.strptime(jsonItem['timestamp'], '%Y-%m-%dT%H:%M:%S')
        timestampObj = timestampObj + 8.hours
        timestampArray.push((timestampObj.change(:offset => '+0800')).to_date)
        timestampArray = timestampArray.uniq.sort()
      end
    end
    @timestampArray = timestampArray
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/nsl_controller.rb
class NslController < ApplicationController
	def index
    jsonFiles = File.read("NSL.json")
    jsonArray = JSON.parse(jsonFiles)
    timestampArray = []
    jsonArray.each do |jsonItem|
      timestampObj = DateTime.strptime(jsonItem['timestamp'], '%Y-%m-%dT%H:%M:%S')
      timestampObj = timestampObj + 8.hours
      timestampArray.push((timestampObj.change(:offset => '+0800')).to_date)
      timestampArray = timestampArray.uniq.sort()
    end
    @timestampArray = timestampArray
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/nsl_helper.rb
module NslHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/bplrt.html.erb
<h1>Bukit Panjang LRT</h1>

<table class="table-condensed">
  <th>
  <% (1..31).each do |i| %>
    <td><%= i %></td>
  <% end %>
  </th>
  <% (Date.new(2017, 01, 01)..Date.new(2017, 12, 31)).each_with_index do |date, index| %>
    <% if date.day == 1%>
    <tr>
      <td class="align-right"><%= date.strftime('%B') %></td>
    <% end %>
      <% if @timestampArray.include? date %>
      <td><div class="breakdown"></div></td>
      <% else %>
      <td><div class="normal"></div></td>
      <% end %>
    <% if date.day == date.end_of_month.day %>
    </tr>
    <% end %>
  <% end %>
</table>

<div class="text-center caption">
  <div class="h-col"></div> Normal
  <div class="h-col false"></div> Breakdown
</div>

app/views/home/ccl.html.erb
<h1>Circle Line</h1>

<table class="table-condensed">
  <th>
  <% (1..31).each do |i| %>
    <td><%= i %></td>
  <% end %>
  </th>
  <% (Date.new(2017, 01, 01)..Date.new(2017, 12, 31)).each_with_index do |date, index| %>
    <% if date.day == 1%>
    <tr>
      <td class="align-right"><%= date.strftime('%B') %></td>
    <% end %>
      <% if @timestampArray.include? date %>
      <td><div class="breakdown"></div></td>
      <% else %>
      <td><div class="normal"></div></td>
      <% end %>
    <% if date.day == date.end_of_month.day %>
    </tr>
    <% end %>
  <% end %>
</table>

<div class="text-center caption">
  <div class="h-col"></div> Normal
  <div class="h-col false"></div> Breakdown
</div>

app/views/home/ewl.html.erb
<h1>East West Line</h1>

<table class="table-condensed">
  <th>
  <% (1..31).each do |i| %>
    <td><%= i %></td>
  <% end %>
  </th>
  <% (Date.new(2017, 01, 01)..Date.new(2017, 12, 31)).each_with_index do |date, index| %>
    <% if date.day == 1%>
    <tr>
      <td class="align-right"><%= date.strftime('%B') %></td>
    <% end %>
      <% if @timestampArray.include? date %>
      <td><div class="breakdown"></div></td>
      <% else %>
      <td><div class="normal"></div></td>
      <% end %>
    <% if date.day == date.end_of_month.day %>
    </tr>
    <% end %>
  <% end %>
</table>

<div class="text-center caption">
  <div class="h-col"></div> Normal
  <div class="h-col false"></div> Breakdown
</div>

app/views/home/index.html.erb
<head>
  <title>Hurizebert</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<% `twitterscraper "[EWL] from:SMRT_Singapore" -bd 2017-01-01 -ed 2017-12-31 -o EWL.json` %>
<% `twitterscraper "[NSL] from:SMRT_Singapore" -bd 2017-01-01 -ed 2017-12-31 -o NSL.json` %>
<% `twitterscraper "[CCL] from:SMRT_Singapore" -bd 2017-01-01 -ed 2017-12-31 -o CCL.json` %>
<% `twitterscraper "[BPLRT] from:SMRT_Singapore" -bd 2017-01-01 -ed 2017-12-31 -o BPLRT.json` %>

<div id="main-container" class="container-fluid main-title">
<h1>SMRT Disruption 2017</h1>
<h2><%= link_to 'EWL', home_ewl_path %></h2>
<h2><%= link_to 'NSL', home_nsl_path %></h2>
<h2><%= link_to 'CCL', home_ccl_path %></h2>
<h2><%= link_to 'BPLRT', home_bplrt_path %></h2>
</div>

app/views/home/nsl.html.erb
<h1>North South Line</h1>

<table class="table-condensed">
  <th>
  <% (1..31).each do |i| %>
    <td><%= i %></td>
  <% end %>
  </th>
  <% (Date.new(2017, 01, 01)..Date.new(2017, 12, 31)).each_with_index do |date, index| %>
    <% if date.day == 1%>
    <tr>
      <td class="align-right"><%= date.strftime('%B') %></td>
    <% end %>
      <% if @timestampArray.include? date %>
      <td><div class="breakdown"></div></td>
      <% else %>
      <td><div class="normal"></div></td>
      <% end %>
    <% if date.day == date.end_of_month.day %>
    </tr>
    <% end %>
  <% end %>
</table>

<div class="text-center caption">
  <div class="h-col"></div> Normal
  <div class="h-col false"></div> Breakdown
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hurizebert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container"  class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <h1>SMRT Disruption 2017</h1>
          <h2><%= link_to 'EWL', home_ewl_path %></h2>
          <h2><%= link_to 'NSL', home_nsl_path %></h2>
          <h2><%= link_to 'CCL', home_ccl_path %></h2>
          <h2><%= link_to 'BPLRT', home_bplrt_path %></h2>
	  <h3><%= link_to 'Home', home_index_path %></h3>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/nsl/home.html.erb
<h1>NSL SMRT Disruption</h1>

<h1><% @timestampArray[1] %></h1>